export const themes = [
  {
    id: "saas-minimal",
    name: "SaaS Minimal",
    tagline: "Clean. Focused. Conversion-driven.",
    origin: "Born from early 2010s SaaS companies like Stripe and Linear",
    typicallyUsed: "B2B software, productivity tools, developer platforms",
    description:
      "The SaaS Minimal theme strips everything down to its essence. White space is a feature, not an absence. Typography does the heavy lifting, and every element earns its place on the page. Pioneered by tools like Stripe and Notion, this style signals trust and professionalism without visual noise.",
    accentColor: "#635BFF",
    bgColor: "#ffffff",
    textColor: "#0a0a0a",
    subtextColor: "#6b7280",
    cardBg: "#f9fafb",
    borderColor: "#e5e7eb",
    style: "minimal",
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    fontNote: "Inter — the quintessential SaaS typeface. Designed for screen legibility, used by Stripe, Linear, Vercel.",
    prompt: `Design a SaaS landing page with a minimal aesthetic. Use a pure white background (#ffffff). Primary accent color is #635BFF (indigo/violet). Typography: use Inter for both headings and body — load from Google Fonts (weights 400, 600, 800). Headlines at 64-80px, font-weight 800, letter-spacing -0.03em. Body text in Inter 400, muted gray (#6b7280). Single primary CTA button (filled, rounded-md, accent color). Below the hero, show 3 feature cards with thin borders, subtle shadow, and icons. Navigation: logo left, 3-4 links center, CTA right. Ample white space throughout. No gradients except a very subtle hero background tint. Grid-based layout. Mobile-first responsive.`,
  },
  {
    id: "ai-dark",
    name: "AI & Deep Tech",
    tagline: "Futuristic. Intelligent. Inevitable.",
    origin: "Emerged with the AI boom of 2022–2024 (OpenAI, Anthropic, Midjourney)",
    typicallyUsed: "AI startups, ML tools, research labs, LLM products",
    description:
      "Dark mode isn't a preference here — it's a statement. The AI Dark theme uses deep navy-to-black backgrounds, animated gradient text, and subtle grid or particle effects to communicate raw intelligence and cutting-edge capability. Companies like OpenAI, Perplexity, and Groq popularized this aesthetic.",
    accentColor: "#00D4FF",
    bgColor: "#050a14",
    textColor: "#ffffff",
    subtextColor: "#94a3b8",
    cardBg: "#0f1a2e",
    borderColor: "#1e3a5f",
    style: "dark",
    fontHeading: "'Space Grotesk', sans-serif",
    fontBody: "'DM Sans', sans-serif",
    fontNote: "Space Grotesk — geometric, slightly irregular, feels engineered. Used by AI and deep-tech products.",
    prompt: `Design a dark-mode AI startup landing page. Background: deep navy-black (#050a14). Primary text: white. Accent: electric cyan (#00D4FF) or a gradient from #00D4FF to #7C3AED. Hero headline should use gradient text (CSS background-clip: text). Typography: Space Grotesk (Google Fonts, weights 500 700) for all headings — geometric and slightly irregular, signals engineered intelligence. DM Sans (weights 400 500) for body text and UI labels. Use JetBrains Mono only for code snippets and metric displays. Add a subtle animated grid or dot-pattern background. Feature cards with dark navy fill (#0f1a2e), thin glowing cyan borders. Add one "glow" effect behind the CTA button. Navigation: dark, glassmorphism-style with backdrop blur. Include a stats row (e.g., "10M+ API calls/day") in bright accent. Subtle particle or line-art animation in hero. Responsive and fast-loading.`,
  },
  {
    id: "fintech-trust",
    name: "FinTech & Trust",
    tagline: "Professional. Secure. Authoritative.",
    origin: "Rooted in traditional banking redesigned by companies like Robinhood, Wise, Brex",
    typicallyUsed: "Neobanks, payment processors, crypto platforms, insurance tech",
    description:
      "FinTech UI borrows trust signals from traditional finance but injects modern clarity. Deep navy paired with gold or green accents conveys reliability and growth. Popularized by Robinhood's approachability and Wise's transparency, this theme balances authority with accessibility. Data visualization and security badges are key supporting elements.",
    accentColor: "#00C896",
    bgColor: "#060d1f",
    textColor: "#f1f5f9",
    subtextColor: "#94a3b8",
    cardBg: "#0d1b36",
    borderColor: "#1e3a5f",
    style: "dark",
    fontHeading: "'Instrument Serif', serif",
    fontBody: "'DM Sans', sans-serif",
    fontNote: "Instrument Serif — editorial authority meets modern finance. Contrasted with DM Sans for readability.",
    prompt: `Design a FinTech landing page that conveys trust and growth. Dark navy background (#060d1f). Accent color: emerald green (#00C896) for positive signals (gains, success). Hero: large number/stat prominently displayed (e.g., "$2.4B processed"). Include a mock dashboard card or chart in the hero section. Typography: Instrument Serif (Google Fonts, weights 400 italic) for all headlines — editorial authority that bridges traditional finance and modern design. DM Sans (weights 400 500 600) for body text, labels, and UI elements. The serif/sans contrast signals both trustworthiness and clarity. Security trust badges row (e.g., SOC2, FDIC, 256-bit encryption icons). Feature list with green checkmarks. CTA: "Get Started Free" in green, secondary "Schedule Demo" as ghost button. Add a subtle upward-trending graph as a decorative background element. Navigation: dark, with a "Login" link and primary CTA. Compliance footer with legal text. Responsive grid layout.`,
  },
  {
    id: "ecommerce-bold",
    name: "E-Commerce & Marketplace",
    tagline: "Bold. Vibrant. Buy-now energy.",
    origin: "Evolved from Shopify, Amazon, and DTC brand identity explosion of 2018–2023",
    typicallyUsed: "Online stores, DTC brands, marketplaces, subscription boxes",
    description:
      "E-commerce design is unapologetically attention-grabbing. High-contrast colors, large product imagery, urgency signals, and social proof are the foundation. The DTC boom brought editorial-style photography and brand storytelling into the mix, creating a hybrid of magazine aesthetics and conversion optimization.",
    accentColor: "#FF4757",
    bgColor: "#ffffff",
    textColor: "#111111",
    subtextColor: "#555555",
    cardBg: "#f8f8f8",
    borderColor: "#e0e0e0",
    style: "bold",
    fontHeading: "'Bebas Neue', sans-serif",
    fontBody: "'Inter', sans-serif",
    fontNote: "Bebas Neue — condensed, punchy, high-energy. The go-to display font for DTC brands and bold campaigns.",
    prompt: `Design an e-commerce or DTC brand landing page. Clean white background with bold, high-contrast typography. Accent: vivid red-orange (#FF4757) for CTAs and sale badges. Typography: Bebas Neue (Google Fonts) for all headlines — condensed, all-caps, punchy. Set at large sizes (80-120px on desktop) with tight letter-spacing (0.02em). Inter (weights 400 600) for all body text, product descriptions, and UI labels. The contrast between Bebas Neue's impact and Inter's legibility is the signature DTC brand formula. Hero: split layout — left side large product photo or lifestyle image, right side headline + CTA. Add urgency element ("Limited stock" or countdown). Below hero: product grid with hover effects, star ratings, and quick-add buttons. Social proof row: customer reviews, press logos. Sticky add-to-cart bar on mobile. Newsletter signup with discount incentive. Footer with trust badges (Free shipping, 30-day returns). Responsive and image-heavy.`,
  },
  {
    id: "edtech-friendly",
    name: "EdTech & Learning",
    tagline: "Curious. Inclusive. Empowering.",
    origin: "Shaped by Duolingo, Coursera, and Khan Academy's accessibility-first designs",
    typicallyUsed: "Online courses, coding bootcamps, tutoring platforms, learning apps",
    description:
      "EdTech design prioritizes approachability and motivation. Bright, friendly colors — often purple, yellow, and teal — paired with rounded shapes and illustrated characters create an inviting environment. Progress indicators, gamification elements, and diverse representation are core to this aesthetic, pioneered by Duolingo and Codecademy.",
    accentColor: "#7C3AED",
    bgColor: "#fafaff",
    textColor: "#1e1b4b",
    subtextColor: "#6b7280",
    cardBg: "#f3f0ff",
    borderColor: "#ddd6fe",
    style: "friendly",
    fontHeading: "'Nunito', sans-serif",
    fontBody: "'Nunito', sans-serif",
    fontNote: "Nunito — rounded terminals and friendly weight range. Used by Duolingo and learning apps for approachability.",
    prompt: `Design an EdTech platform landing page. Light, airy background (#fafaff or soft white). Primary accent: rich purple (#7C3AED), secondary: warm yellow (#FBBF24). Rounded corners everywhere (border-radius: 16-24px). Typography: Nunito (Google Fonts, weights 400 600 700 800 900) for both headings and body text — its rounded terminals and friendly weight range create an approachable, motivating feel used by Duolingo and learning apps. Headlines at font-weight 800-900, body at 400-500. Avoid sharp geometric fonts entirely. Hero: headline with colored text highlight + illustration or diverse character imagery on the right. Add a progress bar or course completion widget as a hero visual. Feature cards with emoji icons, rounded, colorful borders. "How it works" section with numbered steps and playful icons. Social proof: student count + avatar cluster ("Join 50,000+ learners"). Course category pills/chips below hero. Accessible color contrast. Mobile-first responsive.`,
  },
  {
    id: "health-wellness",
    name: "Health & Wellness",
    tagline: "Calm. Clean. Human.",
    origin: "Inspired by Calm, Headspace, and the wellness-tech wave of 2019–2024",
    typicallyUsed: "Mental health apps, fitness platforms, telehealth, nutrition startups",
    description:
      "Health tech design communicates safety, calm, and human connection. Soft sage greens, warm whites, and gentle gradients replace aggressive CTAs with nurturing language. Photography emphasizes real people and natural environments. Companies like Calm, Hims, and One Medical turned clinical coldness into warm, consumer-grade healthcare design.",
    accentColor: "#10b981",
    bgColor: "#f8fdf9",
    textColor: "#1a2e22",
    subtextColor: "#6b7280",
    cardBg: "#edf7f0",
    borderColor: "#bbf7d0",
    style: "calm",
    fontHeading: "'Lora', serif",
    fontBody: "'DM Sans', sans-serif",
    fontNote: "Lora — a warm, humanist serif for headlines. Signals calm and care. Paired with DM Sans for clean body text.",
    prompt: `Design a health and wellness startup landing page. Soft background: near-white with a subtle green tint (#f8fdf9). Primary: sage green (#10b981), secondary: warm peach or lavender accent. Gentle, organic shapes — use SVG blob or wave dividers between sections. Typography: Lora (Google Fonts, weights 400 500 600 700) for all headlines — a warm, humanist serif that signals calm, care, and human connection. DM Sans (weights 300 400 500) for all body text, navigation, and UI labels — clean without feeling clinical. Never use a cold geometric sans for headlines in this theme. Hero: warm photography (person meditating, nature, or smiling human) on right, empathetic headline left ("Feel better, starting today"). CTA buttons: rounded-full (pill shape), soft green fill. Feature section: icon + short benefit, 3 columns with generous spacing. Testimonial: large pull-quote with avatar. Trust section: "As featured in" press logos. NO harsh shadows. Avoid clinical imagery. Soft drop shadows only. Accessible, warm, inclusive.`,
  },
  {
    id: "developer-tools",
    name: "Developer Tools",
    tagline: "Terminal aesthetics. Zero fluff.",
    origin: "Native to tools like Vercel, Railway, Supabase, and the modern dev-tool renaissance",
    typicallyUsed: "CLIs, APIs, infrastructure platforms, open-source tools, dev productivity",
    description:
      "Developer tool design speaks the language of its users: code. Dark backgrounds, monospace fonts, syntax-highlighted snippets, and terminal animations signal authenticity to technical audiences. Companies like Vercel, Supabase, and Railway have elevated this to an art form — blending dark aesthetics with crisp documentation-style clarity.",
    accentColor: "#22d3ee",
    bgColor: "#0a0a0a",
    textColor: "#ededed",
    subtextColor: "#737373",
    cardBg: "#111111",
    borderColor: "#222222",
    style: "terminal",
    fontHeading: "'JetBrains Mono', monospace",
    fontBody: "'JetBrains Mono', monospace",
    fontNote: "JetBrains Mono — pure monospace for authenticity. Every character speaks developer. Used throughout for full terminal immersion.",
    prompt: `Design a developer tools landing page. Near-black background (#0a0a0a). Text: off-white (#ededed). Accent: bright cyan (#22d3ee) or bright green (#22c55e) for code highlights. Typography: JetBrains Mono (Google Fonts, weights 400 500) used throughout — for headlines, body text, navigation, and code blocks alike. Full monospace immersion signals authenticity to developer audiences. Headlines can be larger (48-64px) but stay monospaced. Use letter-spacing: -0.02em on headings to tighten the mono rhythm. Code blocks get syntax highlighting with a slightly lighter background (#161616). Hero: large monospaced headline, below it a live-looking terminal or code block (syntax highlighted, line numbers). Show a real usage example (e.g., npm install, curl command, or code snippet). Navigation: minimal, just logo + GitHub star count + "Docs" + CTA. CTA: "Start building" — dark with cyan border or filled cyan. Integration logos row (AWS, GitHub, Vercel, Stripe icons). Three feature cards with dark fill, minimal border, code-style content. Include a performance metric bar or benchmark table. Footer: open source badge, GitHub link, Discord community.`,
  },
  {
    id: "sustainability",
    name: "Sustainability & Climate",
    tagline: "Earthy. Purposeful. Mission-driven.",
    origin: "Accelerated by Patagonia, Ecosia, and the climate-tech surge of 2020–2025",
    typicallyUsed: "Climate tech, sustainable products, carbon offsetting, green energy",
    description:
      "Sustainability design communicates authenticity and earth-connection. Earthy tones — forest green, warm terracotta, sandy beige — paired with hand-drawn illustrations and natural textures set this aesthetic apart. Brands like Oatly, Allbirds, and Patch have proven that caring about the planet can also mean beautiful design.",
    accentColor: "#4d7c0f",
    bgColor: "#fafaf5",
    textColor: "#1a2e05",
    subtextColor: "#57764a",
    cardBg: "#f0f4e8",
    borderColor: "#d1e8b4",
    style: "earthy",
    fontHeading: "'Playfair Display', serif",
    fontBody: "'Lora', serif",
    fontNote: "Playfair Display — editorial elegance and timeless authority. Paired with Lora for an organic, print-magazine warmth.",
    prompt: `Design a sustainability or climate-tech startup landing page. Warm off-white background (#fafaf5) with earthy, organic feel. Primary: forest green (#4d7c0f), secondary: terracotta (#c2410c) or sandy yellow (#d97706). Organic, imperfect shapes — hand-drawn SVG borders, leaf motifs, or brush-stroke dividers. Typography: Playfair Display (Google Fonts, weights 400 700 800) for all headlines — its high-contrast strokes and editorial elegance give authority without corporate coldness. Lora (weights 400 500) for all body text and captions — a serif that feels warm and readable, like a well-designed print magazine. Avoid sans-serif fonts entirely in this theme; the all-serif pairing reinforces authenticity and craft. Hero: nature photography (aerial forest, ocean, or renewable energy) with warm overlay. Headline: large, bold, mission-forward ("We're reversing climate change, one tonne at a time"). Impact counter: CO₂ offset, trees planted, kWh generated — displayed as animated stats. Feature cards with texture-style backgrounds and earthy icons. Partner logos. Manifesto-style about section. No fluorescent colors. Warm, authentic, imperfect > slick and corporate.`,
  },
  {
    id: "social-community",
    name: "Social & Community",
    tagline: "Warm. Connected. Human-first.",
    origin: "Influenced by Discord, Luma, Beehiiv, and the creator economy boom",
    typicallyUsed: "Community platforms, social apps, newsletters, creator tools, event platforms",
    description:
      "Community-focused design radiates energy and belonging. Warm gradients, avatar clusters, user-generated content previews, and high-energy typography signal an active, thriving community. Discord's playful rebrand, Luma's elegant event design, and Beehiiv's newsletter-first aesthetic have defined this space.",
    accentColor: "#f59e0b",
    bgColor: "#fffbf0",
    textColor: "#1c1917",
    subtextColor: "#78716c",
    cardBg: "#fef3c7",
    borderColor: "#fde68a",
    style: "warm",
    fontHeading: "'Plus Jakarta Sans', sans-serif",
    fontBody: "'Plus Jakarta Sans', sans-serif",
    fontNote: "Plus Jakarta Sans — modern, confident, and slightly expressive. Used by creator platforms and community-first products.",
    prompt: `Design a social community or creator platform landing page. Warm, sunny background (#fffbf0). Primary accent: amber/gold (#f59e0b), secondary: vibrant coral or rose. Typography: Plus Jakarta Sans (Google Fonts, weights 400 500 600 700 800) for both headings and body — modern and confident with a slightly expressive character that feels human without being childish. Used by creator platforms and community-first products. Headlines at font-weight 700-800, body at 400-500. The slightly wide letter-spacing at large sizes adds energy. Hero: show a cluster of member avatars or a "wall" of community posts/messages. Headline: energetic, second-person ("The place your community has been waiting for"). Add a live activity feed widget or "X members joined this week" counter. Feature highlights with warm-toned cards and emoji icons. Testimonial carousel with member photos and quotes. Pricing section with a "most popular" highlighted card. CTA: warm amber gradient button with high contrast text. Rounded shapes, no sharp corners. Include a community photo grid or user-generated content mosaic. High energy, inclusive, joyful.`,
  },
  {
    id: "gaming-entertainment",
    name: "Gaming & Entertainment",
    tagline: "Neon. Kinetic. Immersive.",
    origin: "Shaped by Twitch, Epic Games, Riot Games, and streaming-era visual identity",
    typicallyUsed: "Gaming platforms, esports, streaming tools, entertainment apps, metaverse",
    description:
      "Gaming design is built for impact. Neon accents on near-black backgrounds, aggressive typography, animated elements, and character art create a sense of kinetic energy. Twitch's purple, Riot's editorial boldness, and Epic's cinematic scale define this genre. Nothing is subtle — everything demands attention.",
    accentColor: "#a855f7",
    bgColor: "#07020f",
    textColor: "#ffffff",
    subtextColor: "#a78bfa",
    cardBg: "#130a2a",
    borderColor: "#2d1b69",
    style: "neon",
    fontHeading: "'Bebas Neue', sans-serif",
    fontBody: "'Barlow Condensed', sans-serif",
    fontNote: "Bebas Neue + Barlow Condensed — maximum impact. Condensed display fonts used by Epic Games, Riot, and esports brands.",
    prompt: `Design a gaming or entertainment platform landing page. Near-black dark purple background (#07020f). Neon accents: electric purple (#a855f7), hot pink (#ec4899), and electric blue (#3b82f6). Typography: Bebas Neue (Google Fonts) for all headlines — all-caps, condensed, maximum visual weight. Set at massive scale (100-160px on desktop). Barlow Condensed (weights 400 500 600 700) for subheadings, body text, nav links, and UI labels — it shares Bebas Neue's condensed DNA but has lowercase and full weight range for readability. Both fonts should feel like they belong on a stadium screen or esports jersey. Never use a rounded or friendly font in this theme. Hero: cinematic full-width background (character art, game screenshot, or abstract neon render) with a dark overlay. Headline all-caps, massive. CTA: glowing purple button with a neon border-glow effect (box-shadow). Add neon line-art or geometric grid overlays. Feature section: dark cards with neon icon accents and glow effects on hover. Stats row: player count, matches played, revenue — displayed in neon digits. Navigation: fully transparent, sticky, with a glowing active indicator. Chrome/holographic text effect for key words. Aggressive, immersive, electric.`,
  },
];
